language: c++
sudo: true
script: cd secp256k1 && ./autogen.sh && ./configure && make && make install && cd .. && cmake . && make
addons:
  apt:
    packages:
      - cmake
compiler:
  - clang++
  - g++
