language: c++
sudo: false
script: cd secp256k1 && ./autogen.sh && ./configure && make && cd .. && cmake . && make && ./ecdsa_test
addons:
  apt:
    packages:
      - cmake
compiler:
  - clang++
  - g++
